name: simoncalling
favicon: null
layout_spectrum: 0.06429833825677633
typography_spectrum: 0.2569383087102324
title: 'Simon calling '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.4203413431532681
  lightness: 0.6902161065954715
  saturation: 0.7112789773382246
  rhythmicContrast: 0.4455631673336029
purpose: []
